CREATE TABLE machine_classifier (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    classifier_id TEXT NOT NULL, -- ID_классификатора (хеш раздела и группы)
    section TEXT NOT NULL,       -- Раздел
    group_name TEXT NOT NULL,    -- Группа
    code TEXT NOT NULL UNIQUE,   -- Код
    name TEXT NOT NULL           -- Название
);

CREATE TABLE work_classifier (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sphere TEXT NOT NULL,                         -- Сфера
    document TEXT NOT NULL,                       -- Документ
    collection TEXT NOT NULL,                     -- Сборник
    department TEXT,                              -- Раздел
    section TEXT,                                 -- Секция
    subsection TEXT,                              -- Подсекция
    table_code TEXT NOT NULL,                     -- Код таблицы
    table_name TEXT NOT NULL,                     -- Название таблицы
    work_code TEXT NOT NULL,                      -- Код работы
    work_name TEXT NOT NULL,                      -- Название работы
    unit TEXT NOT NULL,                           -- Единица измерения
    workers_hours DOUBLE PRECISION,               -- Трудозатраты рабочих (чел/ч)
    machinists_hours DOUBLE PRECISION,            -- Трудозатраты машинистов (чел/ч)
    commissioning_hours DOUBLE PRECISION,         -- Трудозатраты пусконаладки (чел/ч)
    labor_hours DOUBLE PRECISION,                 -- Суммарные трудозатраты
    machines_hours DOUBLE PRECISION,              -- Машинное время (итог по норме)
    machine_id UUID REFERENCES machine_classifier (id) ON DELETE SET NULL, -- вместо «Код машины»
    machine_hours DOUBLE PRECISION                -- Машинное время (на норму)
);

CREATE INDEX work_classifier_machine_id_idx ON work_classifier (machine_id);

CREATE TABLE detected_classes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model TEXT NOT NULL,        -- идентификатор модели с HugginFace или Torch
    class INTEGER NOT NULL,     -- id класса внутри модели
    class_name TEXT             -- название класса внутри модели
);

CREATE TABLE detected_class_machine (
    detected_class_id INTEGER NOT NULL REFERENCES detected_classes (id) ON DELETE CASCADE,
    machine_id UUID NOT NULL REFERENCES machine_classifier (id) ON DELETE CASCADE,
    PRIMARY KEY (detected_class_id, machine_id)
);

CREATE INDEX detected_class_machine_machine_id_idx ON detected_class_machine (machine_id);
